spring.application.name=spring-boot-basic

#logging.level.com.hyundaimotorgroup.springboot.basic.lifecycle=INFO
spring.threads.virtual.enabled=true

spring.cache.redis.key-prefix=${spring.application.name}::
spring.cache.redis.time-to-live=10s

spring.config.source=classpath:/application.properties

app.manager.first-name=MinJeong
app.manager.last-name=Kim
app.staffs.developer.first-name=JinYeong
app.staffs.developer.last-name=Yoo
app.staffs.designer.first-name=JongHyi
app.staffs.designer.last-name=Park

management.endpoint.env.show-values=always
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.readiness.include=readinessState

management.server.port=8081
# build, git info? ??? ?????.
#management.info.build.enabled=true
#management.info.git.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
management.info.process.enabled=true

#management.health.redis.enabled=false




