spring.application.name=spring-boot-basic

#logging.level.com.hyundaimotorgroup.springboot.basic.lifecycle=INFO
spring.threads.virtual.enabled=true

# FIXME: 2. Config Properties ??
spring.config.source=classpath:/application.properties



